services:
  - type: web
    name: aibriefai
    runtime: static
    repo: https://github.com/f2h2dai/AibriefAI.git
    branch: main
    buildCommand: ""
    staticPublishPath: ./web
    autoDeployTrigger: commit
